name: C 
on:   
  workflow_dispatch:

jobs:
  fizzbuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Update apt and install C toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            gdb \
            valgrind \
            cmake

      - name: Show tool versions
        run: |
          gcc --version
          g++ --version
          gdb --version
          valgrind --version
          cmake --version

      # Optional: build & run a tiny C sample to verify everything works
      - name: Compile and run sample
        run: |
          mkdir -p build
          gcc -o ./build/main "main.c"
          ./build/main

