name: test2

on:
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  fizzbuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        run: curl -L https://github.com/evanallen13/C-Container/releases/download/latest/main --output main

      - name: Run
        run: |
          chmod +x main
          ./main
