name: Test

on:
  workflow_dispatch:
  
jobs:
  fizzbuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        run: curl -L https://github.com/evanallen13/C-Container/releases/download/latest/main --output main

      - name: Run
        run: |
          ls
          # chmod +x main
          # ./main
