name: Test

on:
  workflow_dispatch:
    inputs: 
      release:
        description: 'Release version to test'
        required: true
        default: 'latest'

  workflow_call:
    inputs: 
      release:
        description: 'Release version to test'
        required: true
        default: 'latest'
        type: string

  
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        run: |
          gh release download ${{ inputs.release }} --repo evanallen13/C-Container
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Run
        run: |
          ls
          chmod +x main
          ./main
